apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-html
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/c/Users/oscar.avendano/Desktop/The Farm/Pracica_Volumenes/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-html
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    Tusken: hello-app  # Arreglado indentación aquí
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html-volume
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: pvc-html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    Tusken: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
