name: "Terraform Destroy"

on:
  workflow_dispatch: # Permite ejecutar manualmente el workflow desde la interfaz de GitHub

env:
  TF_CLOUD_ORGANIZATION: "Sehent"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "learn-terraform-github-actions"
  CONFIG_DIRECTORY: "./"

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Print Environment Variables
        run: |
          echo "TF_CLOUD_ORGANIZATION: $TF_CLOUD_ORGANIZATION"
          echo "TF_API_TOKEN (first 4 and last 4 characters): ${TF_API_TOKEN:0:4}****${TF_API_TOKEN: -4}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
